### ISSUE TITLE
Rounding NJS to 2 decimal places

### ISSUE THREAD

**Issue by CAT-EJ** [Auros/LevelTweaks#2]
![Level tweaks problem](https://user-images.githubusercontent.com/78929591/107685211-bc3ab380-6c71-11eb-9a5c-fc5ab9b9f80b.JPG)

The recently ranked level sAtAN has a default NJS of 22.666, when going to create a custom offset for this song, the plugin rounds the song's NJS to 22.67, disabling score submission for the level.

**Comment by Auros** [comment]
Sorry it took me so long to address this, it slipped my mind. I have fixed it and will be releasing a new version soon.
